"""
inference/serialization_utils.py
─────────────────────────────────
Bidirectional serialization between:
  A. OSPPayload (Python dataclass, engine.py)   ← internal runtime object
  B. SceneBrief (Protobuf binary)               ← satellite downlink wire format
  C. JSON string                                 ← analyst dashboard format

Wire format selection rationale:
  - Binary (.bin) is used for the RF downlink: minimal bytes over the air.
  - JSON  (.json) is generated ground-side from the deserialized proto:
    the dashboard never sees raw binary, keeping it portable.

Field mapping (OSPPayload → SceneBrief proto):
  OSPPayload.scene_id         → SceneBrief.scene_id
  OSPPayload.timestamp_utc    → SceneBrief.timestamp_utc
  OSPPayload.tile_footprint   → SceneBrief.tile_footprint (TileFootprint msg)
  OSPPayload.cloud_cover      → SceneBrief.cloud_cover
  OSPPayload.inference_ms     → SceneBrief.inference_ms
  OSPPayload.model_version    → SceneBrief.model_version
  OSPPayload.compression_ratio→ SceneBrief.compression_ratio
  Anomaly.type  (str)         → Anomaly.type  (AnomalyType enum)
  Anomaly.conf  (float)       → Anomaly.confidence  ← NOTE: renamed in proto
  Anomaly.bbox_px (list[int]) → Anomaly.bbox_px (repeated int32)

CRITICAL: Anomaly.conf in the dataclass → Anomaly.confidence in proto.
          This rename was intentional (proto field names must be unambiguous).
          The mapping is enforced here and asserted in test_pipeline.py.
"""

import json
import logging
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

log = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO, format="%(levelname)s | %(message)s")

# ── Proto imports (generated by compile_proto.sh) ─────────────────────────────
try:
    from osp_pb2 import (
        Anomaly     as ProtoAnomaly,
        AnomalyType,
        SceneBrief,
        TileFootprint,
    )
except ImportError as e:
    raise ImportError(
        f"Proto classes not found: {e}\n"
        "Run: ./compile_proto.sh  (or: python -m grpc_tools.protoc -I. --python_out=inference osp.proto)"
    ) from e


# ── String ↔ AnomalyType enum mapping ────────────────────────────────────────

_STR_TO_ENUM: dict[str, int] = {
    "ship":         AnomalyType.SHIP,
    "airplane":     AnomalyType.AIRPLANE,
    "storage-tank": AnomalyType.STORAGE_TANK,
    "harbor":       AnomalyType.HARBOR,
}

_ENUM_TO_STR: dict[int, str] = {v: k for k, v in _STR_TO_ENUM.items()}


def str_to_anomaly_type(name: str) -> int:
    """Convert class name string → AnomalyType enum int. Unknown → UNKNOWN(0)."""
    return _STR_TO_ENUM.get(name.lower().strip(), AnomalyType.UNKNOWN)


def anomaly_type_to_str(enum_val: int) -> str:
    """Convert AnomalyType enum int → class name string."""
    return _ENUM_TO_STR.get(enum_val, "unknown")


# ── OSPPayload → SceneBrief (proto) ──────────────────────────────────────────

def payload_to_proto(payload) -> SceneBrief:
    """
    Convert an engine.OSPPayload dataclass → SceneBrief proto message.

    Args:
        payload: engine.OSPPayload instance (imported lazily to avoid circular)

    Returns:
        SceneBrief proto message, ready for SerializeToString()
    """
    fp = payload.tile_footprint  # plain dict

    proto_footprint = TileFootprint(
        lat_min=float(fp.get("lat_min", 0.0)),
        lat_max=float(fp.get("lat_max", 0.0)),
        lon_min=float(fp.get("lon_min", 0.0)),
        lon_max=float(fp.get("lon_max", 0.0)),
    )

    proto_anomalies = []
    for a in payload.anomalies:
        bbox = a.bbox_px
        if len(bbox) != 4:
            log.warning(
                f"Anomaly bbox_px has {len(bbox)} elements (expected 4). "
                "Padding/truncating to 4."
            )
            bbox = (list(bbox) + [0, 0, 0, 0])[:4]

        proto_anomalies.append(ProtoAnomaly(
            type       = str_to_anomaly_type(a.type),
            lat        = float(a.lat),
            lon        = float(a.lon),
            confidence = float(a.conf),     # dataclass field is .conf
            bbox_px    = [int(x) for x in bbox],
        ))

    brief = SceneBrief(
        scene_id          = str(payload.scene_id),
        timestamp_utc     = str(payload.timestamp_utc),
        tile_footprint    = proto_footprint,
        cloud_cover       = float(payload.cloud_cover),
        anomalies         = proto_anomalies,
        inference_ms      = float(payload.inference_ms),
        model_version     = str(payload.model_version),
        compression_ratio = int(payload.compression_ratio),
    )

    return brief


# ── SceneBrief → OSPPayload (reconstruct dataclass) ──────────────────────────

def proto_to_payload(brief: SceneBrief):
    """
    Deserialize SceneBrief proto → engine.OSPPayload dataclass.
    Used ground-side after receiving binary downlink.

    Returns engine.OSPPayload (imported lazily).
    """
    # Lazy import to avoid circular dependency (absolute path for portability)
    import sys as _sys, os as _os
    _sys.path.insert(0, _os.path.dirname(_os.path.abspath(__file__)))
    from engine import Anomaly as EngineAnomaly, OSPPayload

    footprint = {
        "lat_min": brief.tile_footprint.lat_min,
        "lat_max": brief.tile_footprint.lat_max,
        "lon_min": brief.tile_footprint.lon_min,
        "lon_max": brief.tile_footprint.lon_max,
    }

    anomalies = []
    for pa in brief.anomalies:
        anomalies.append(EngineAnomaly(
            type    = anomaly_type_to_str(pa.type),
            lat     = pa.lat,
            lon     = pa.lon,
            conf    = pa.confidence,          # proto → .conf in dataclass
            bbox_px = list(pa.bbox_px),
        ))

    return OSPPayload(
        scene_id          = brief.scene_id,
        timestamp_utc     = brief.timestamp_utc,
        tile_footprint    = footprint,
        cloud_cover       = brief.cloud_cover,
        anomalies         = anomalies,
        inference_ms      = brief.inference_ms,
        model_version     = brief.model_version,
        compression_ratio = brief.compression_ratio,
    )


# ── Serialize / Deserialize ───────────────────────────────────────────────────

def serialize_to_binary(payload, out_path: Optional[str] = None) -> bytes:
    """
    Serialize OSPPayload → Protobuf binary bytes.
    Optionally write to .bin file (OrbitLab output mount: /output/{scene_id}.bin).
    """
    brief  = payload_to_proto(payload)
    binary = brief.SerializeToString()

    if out_path:
        Path(out_path).write_bytes(binary)
        log.info(f"Binary downlink written: {out_path} ({len(binary)} bytes)")

    return binary


def deserialize_from_binary(binary: bytes):
    """
    Deserialize Protobuf binary bytes → OSPPayload dataclass.
    Called ground-side after RF receive.
    """
    brief = SceneBrief()
    brief.ParseFromString(binary)
    return proto_to_payload(brief)


def payload_to_json(payload) -> str:
    """
    Serialize OSPPayload → compact JSON string (dashboard format).
    Goes through proto and back to guarantee JSON ↔ binary field parity.
    """
    brief = payload_to_proto(payload)
    return _proto_to_json_str(brief)


def _proto_to_json_str(brief: SceneBrief) -> str:
    """
    Convert SceneBrief proto → compact JSON dict.
    Mirrors engine.OSPPayload.to_json() schema exactly so the dashboard
    doesn't need two JSON parsers.
    """
    d = {
        "scene_id":      brief.scene_id,
        "timestamp_utc": brief.timestamp_utc,
        "tile_footprint": {
            "lat_min": brief.tile_footprint.lat_min,
            "lat_max": brief.tile_footprint.lat_max,
            "lon_min": brief.tile_footprint.lon_min,
            "lon_max": brief.tile_footprint.lon_max,
        },
        "cloud_cover":   round(brief.cloud_cover, 3),
        "anomaly_count": len(brief.anomalies),
        "anomalies": [
            {
                "type":    anomaly_type_to_str(a.type),
                "lat_lon": [round(a.lat, 6), round(a.lon, 6)],
                "conf":    round(a.confidence, 4),
                "bbox_px": list(a.bbox_px),
            }
            for a in brief.anomalies
        ],
        "meta": {
            "model_version":    brief.model_version,
            "inference_ms":     round(brief.inference_ms, 1),
            "compression_ratio": brief.compression_ratio,
        },
    }
    return json.dumps(d, separators=(",", ":"))


# ── Compression report ────────────────────────────────────────────────────────

@dataclass
class CompressionReport:
    scene_id:              str
    raw_tile_bytes:        int     # 640×640×6×4 float32
    raw_scene_bytes:       int     # 100 MB nominal full Sentinel-2 scene
    json_bytes:            int
    proto_bytes:           int
    proto_vs_json_ratio:   float   # how much smaller proto is than JSON
    json_vs_raw_tile:      float   # JSON compression ratio vs tile
    proto_vs_raw_tile:     float   # proto compression ratio vs tile
    proto_vs_raw_scene:    float   # proto vs full 100 MB scene (headline)
    latency_ok:            bool    # inference_ms < 800
    size_ok:               bool    # proto < 2 KB (PRD target)

    def __str__(self) -> str:
        bar = "─" * 52
        return (
            f"\n{bar}\n"
            f"  OSP Compression Report — {self.scene_id}\n"
            f"{bar}\n"
            f"  Raw tile  (640×640×6 float32): {self.raw_tile_bytes:>10,} B  "
            f"({self.raw_tile_bytes/1e6:.2f} MB)\n"
            f"  Raw scene (100 MB Sentinel-2): {self.raw_scene_bytes:>10,} B  "
            f"(100.00 MB)\n"
            f"  JSON payload               :   {self.json_bytes:>10,} B\n"
            f"  Proto binary               :   {self.proto_bytes:>10,} B\n"
            f"{bar}\n"
            f"  Proto vs JSON              :   {self.proto_vs_json_ratio:>8.1f}× smaller\n"
            f"  JSON  vs raw tile          :   {self.json_vs_raw_tile:>8,.0f}:1\n"
            f"  Proto vs raw tile          :   {self.proto_vs_raw_tile:>8,.0f}:1\n"
            f"  Proto vs raw scene (100MB) :   {self.proto_vs_raw_scene:>8,.0f}:1\n"
            f"{bar}\n"
            f"  <800ms latency target      :   {'✓ MET' if self.latency_ok else '✗ MISSED'}\n"
            f"  <2KB proto size target     :   {'✓ MET' if self.size_ok else '✗ MISSED'}\n"
            f"{bar}\n"
        )


def get_compression_report(payload) -> CompressionReport:
    """
    Compare JSON vs Protobuf byte sizes for an OSPPayload.
    Returns a CompressionReport with all ratios computed.

    This is the function you demo in the pitch — shows exactly why binary
    proto is the right downlink format.
    """
    json_str   = payload.to_json()
    binary     = serialize_to_binary(payload)

    json_bytes  = len(json_str.encode("utf-8"))
    proto_bytes = len(binary)

    # Raw tile: 640×640 px × 6 bands × 4 bytes (float32)
    raw_tile_bytes  = 640 * 640 * 6 * 4          # ~9.83 MB

    # Nominal full Sentinel-2 L2A scene (industry standard reference)
    raw_scene_bytes = 100 * 1024 * 1024          # 100 MB

    report = CompressionReport(
        scene_id             = payload.scene_id,
        raw_tile_bytes       = raw_tile_bytes,
        raw_scene_bytes      = raw_scene_bytes,
        json_bytes           = json_bytes,
        proto_bytes          = proto_bytes,
        proto_vs_json_ratio  = json_bytes / max(1, proto_bytes),
        json_vs_raw_tile     = raw_tile_bytes / max(1, json_bytes),
        proto_vs_raw_tile    = raw_tile_bytes / max(1, proto_bytes),
        proto_vs_raw_scene   = raw_scene_bytes / max(1, proto_bytes),
        latency_ok           = payload.inference_ms < 800.0,
        size_ok              = proto_bytes < 2048,   # PRD: <2 KB downlink payload
    )

    return report


# ── CLI demo ──────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    """
    Demo: build a mock OSPPayload, serialize both ways, print report.
    Does NOT require a trained model or ONNX runtime.
    """
    import sys
    sys.path.insert(0, str(Path(__file__).parent))
    from engine import Anomaly as EngineAnomaly, OSPPayload

    mock_payload = OSPPayload(
        scene_id      = "OSP-DEMO-01",
        timestamp_utc = "2026-04-24T09:12:44Z",
        tile_footprint = {"lat_min": 8.0, "lat_max": 9.0,
                          "lon_min": 77.0, "lon_max": 78.0},
        cloud_cover    = 0.08,
        anomalies=[
            EngineAnomaly("ship",    lat=8.412, lon=77.821, conf=0.87,
                          bbox_px=[320, 210, 380, 250]),
            EngineAnomaly("ship",    lat=8.388, lon=77.795, conf=0.79,
                          bbox_px=[280, 300, 340, 330]),
            EngineAnomaly("harbor",  lat=8.501, lon=77.901, conf=0.92,
                          bbox_px=[450, 140, 560, 220]),
        ],
        inference_ms      = 312.4,
        model_version     = "osp-yolov8n-int8-v1",
        compression_ratio = 85000,
    )

    # Serialize
    binary   = serialize_to_binary(mock_payload)
    json_str = payload_to_json(mock_payload)

    print(f"Proto binary : {binary.hex()[:64]}...")
    print(f"JSON snippet : {json_str[:120]}...")

    # Round-trip verification
    recovered = deserialize_from_binary(binary)
    assert recovered.scene_id == mock_payload.scene_id
    assert len(recovered.anomalies) == len(mock_payload.anomalies)
    assert abs(recovered.anomalies[0].conf - 0.87) < 1e-4
    assert recovered.anomalies[0].type == "ship"
    assert list(recovered.anomalies[0].bbox_px) == [320, 210, 380, 250]
    print("\n✓ Round-trip: binary → OSPPayload → verified\n")

    # Compression report
    report = get_compression_report(mock_payload)
    print(report)